# frozen_string_literal: true

require "json"
require "pathname"

require "ucode/repo/atomic_writes"

module Ucode
  module Site
    # Writes `site/.vitepress/config.ts` from the JSON output tree.
    #
    # Reads:
    #   output/planes/<n>.json     → top nav (17 planes)
    #   output/blocks/index.json   → sidebar groups (one per plane)
    #
    # Writes:
    #   site/.vitepress/config.ts  — TypeScript module that exports the
    #   Vitepress `defineConfig` payload. Idempotent via AtomicWrites.
    #
    # **Pure**: reads JSON, writes TS. No Vitepress dependency on the
    # Ruby side; the site is a thin shell that imports this generated
    # config and re-exports `defineConfig(config)`.
    class ConfigEmitter
      include Repo::AtomicWrites

      # @param output_root [String, Pathname] dataset root
      # @param site_root [String, Pathname] Vitepress project root
      def initialize(output_root:, site_root:)
        @output_root = Pathname.new(output_root)
        @site_root = Pathname.new(site_root)
      end

      # @return [Pathname] the config file path that #emit writes
      def target_path
        @site_root.join(".vitepress", "config.ts")
      end

      # Read the output tree, render config.ts, write atomically.
      # @return [Boolean] true if the file was (re)written, false if skipped
      def emit
        write_atomic(target_path, render(load_planes, load_blocks))
      end

      private

      def load_planes
        (0..16).map do |n|
          path = @output_root.join("planes", "#{n}.json")
          next nil unless path.exist?

          JSON.parse(path.read).tap do |plane|
            plane["number"] = n
          end
        end.compact
      end

      def load_blocks
        path = @output_root.join("blocks", "index.json")
        return [] unless path.exist?

        JSON.parse(path.read)
      end

      def render(planes, blocks)
        <<~TS
          // AUTO-GENERATED by Ucode::Site::ConfigEmitter. Do not edit.
          import { defineConfig } from "vitepress";

          export const planes = #{planes_to_ts(planes)};

          export const blocks = #{blocks_to_ts(blocks)};

          export default defineConfig({
            title: "ucode",
            description: "Unicode Character Database — code charts, properties, relationships",
            cleanUrls: true,
            themeConfig: {
              siteTitle: "ucode",
              nav: [
                { text: "Planes", link: "/plane/0" },
                { text: "Search", link: "/search" },
              ],
              sidebar: sidebar(planes, blocks),
              socialLinks: [
                { icon: "github", link: "https://github.com/fontist/ucode" },
              ],
              search: { provider: "local" },
            },
          });

          function sidebar(planes, blocks) {
            const groups = {};
            for (const plane of planes) {
              groups[plane.number] = {
                text: plane.abbrev + " — " + plane.name,
                items: blocks
                  .filter((b) => b.plane_number === plane.number)
                  .map((b) => ({ text: b.name, link: "/block/" + b.id })),
              };
            }
            // Sidebar per top-level section: plane pages share one sidebar,
            // block pages get their plane's sidebar.
            return {
              "/plane/": Object.values(groups),
              "/block/": groups,
            };
          }
        TS
      end

      def planes_to_ts(planes)
        JSON.pretty_generate(planes.map { |p|
          { number: p["number"], name: p["name"], abbrev: p["abbrev"] }
        })
      end

      def blocks_to_ts(blocks)
        JSON.pretty_generate(blocks.map { |b|
          { id: b["id"], name: b["name"], plane_number: b["plane_number"] }
        })
      end
    end
  end
end
